node {   
  stage('Git-Checkout') {
   git 'https://github.com/Pranay-26/terraform.git'
  }
   stage('ansible-deploy') {
   sh 'ansible-playbook  --key=/var/lib/jenkins/.ssh/aws.pem -i inventory ./ansible/04-Tomcat/web-playbook.yml -u ubuntu -v'
  }
  