node {   
  stage('Git-Checkout') {
   git 'https://github.com/Pranay-26/terraform.git'
  }
  
  def project_ansible="ansible-01/"
dir(project_ansible) {
   stage('ansible-deploy') {
   sh 'ansible-playbook  --key=/var/lib/jenkins/.ssh/aws.pem -i inventory web-playbook.yml -u ubuntu -v'
  }
  }
}